### ISSUE TITLE
feature request: multiple template structures for GCN module

### ISSUE THREAD

**Issue by tkosciol** [bioinf-mcb/Metagenomic-DeepFRI#1]
in the case where there are multiple non-overlapping or partially overlapping hits in the MMSeqs2 step, pick all templates and merge them.
For example, the query is a 300 residue protein (1-300). TemplateA hits residues 1-200 and TemplateB hits 150-300. We would like to use both, because they cover different parts of the query.

@PawelSzczerbiak it is partly similar to what we were doing the the microprot pipeline, so maybe bottowing some of the subroutines from there would make sense?

**Comment by PawelSzczerbiak** [comment]
Do you mean [this](https://github.com/biocore/microprot/blob/master/microprot/scripts/split_search.py)? Maybe it's worth checking out.

**Comment by valentynbez** [comment]
@tkosciol do we still go with this one? It seems like we'll mostly be able to find similar queries.

**Comment by tkosciol** [comment]
quite likely but some test/evaluation on a real dataset that this is indeed the case would help.
I would like to be sure that we are not picking up partial matches
