### ISSUE TITLE
"pos_weight" in train_DeepFRI.model

### ISSUE THREAD

**Issue by comeon01** [bioinf-mcb/Metagenomic-DeepFRI#11]
In my opinion, pos_weight is to solve the problem of sample imbalance, but it doesn't seem to work. I put it in model.train(), There are errors . Do you have any suggestions

**Comment by SoliareofAstora** [comment]
This project is using already trained DeepFRI model as pipeline element. 
For more information about this model and training procedures go to the [flatironinstitute/DeepFRI](https://github.com/flatironinstitute/DeepFRI) repository.

**Comment by comeon01** [comment]
Ok, thank you for your reply.
