### ISSUE TITLE
ENH: replace structure lookup with EMBER3D

### ISSUE THREAD

**Issue by tkosciol** [bioinf-mcb/Metagenomic-DeepFRI#19]
we might consider replacing the lookup in AF2 DB for [EMBER3D](https://github.com/kWeissenow/EMBER3D). Or, alternatively, to lookup first and if no structure is found generate it on the fly with EMBER3D.

I would love to see what @VGligorijevic thinks

**Comment by valentynbez** [comment]
Closing it for now, as we discussed sticking to the current strategy. Feel free to reopen if you'll have new ideas.
