### ISSUE TITLE
`parse_mmcif` fails to give adequate outputs

### ISSUE THREAD

**Issue by valentynbez** [bioinf-mcb/Metagenomic-DeepFRI#26]
`mmcif` format does not contain sequence data, which will cause the database build to fail. Two ways: 

- deprecate it and remove (I think pdb is much more common anyways)
- add function to load corresponding FASTA data

Look for test data: https://github.com/valentynbez/Metagenomic-DeepFRI/tree/folder-structure-patch
What do you think @tkosciol?

**Comment by tkosciol** [comment]
`mmcif` must stay as it is a de facto standard for structure files and despite `pdb` popularity it is preferred now.  

note, regardless if the `mmcif` or `pdb` file is provided, if there is no sequence information the sequence should be read from `ATOM` records in the PDB file. for example, by indexing CA atoms. reading sequence from the sequence records may result in a mismatch between sequence residues and structure residues (unresolved residues, chopped off, etc.)

**Comment by valentynbez** [comment]
Resolved in #32
