### ISSUE TITLE
Error with Foldcomp databases (AttributeError: 'pyopal.lib.Database' object has no attribute 'search')

### ISSUE THREAD

**Issue by lmszydlowski** [bioinf-mcb/Metagenomic-DeepFRI#68]
[log.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14037344/log.txt)

**Comment by lmszydlowski** [comment]
I downloaded both afdb_swissprot and highquality_clust30, none of them worked due to the error as given in log

**Comment by valentynbez** [comment]
What version of `pyopal` do you use? 
I see that new release had a lot of API changes, I will need to look for them in detail.

**Comment by lmszydlowski** [comment]
Hi,

I checked and have pyopal 0.5.1 installed.

**Comment by valentynbez** [comment]
You can downgrade `pyopal` to version `0.4` now. I'm currently working on a fix.
