### ISSUE TITLE
gcc: error: unrecognized command line option ‘-std=c++17’

### ISSUE THREAD

**Issue by jiaojiaoguan** [bioinf-mcb/Metagenomic-DeepFRI#69]
Dear all,

Thanks very much for your excellent work.

when I run` pip install .`,  it has a error like this,
`gcc: error: unrecognized command line option ‘-std=c++17’
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mDeepFRI
Failed to build mDeepFRI
ERROR: Could not build wheels for mDeepFRI, which is required to install pyproject.toml-based projects`

I know that it means the gcc version is too low. It seems that updating the gcc needs the root account. 
Do you have any suggestions about it?

Thanks very much for your help!

**Comment by valentynbez** [comment]
Hello, 
You can install different versions of `gcc` in a conda environment, which you should create before anyway for satisfying dependencies. And then use `pip install .`
