### ISSUE TITLE
Update docker image repository name

### ISSUE THREAD

**Issue by SoliareofAstora** [bioinf-mcb/Metagenomic-DeepFRI#7]
In the README there is docker image linked to my personal repository. In the future you will be unable to update it. 

docker run -it -u $(id -u):$(id -g) -v /YOUR_DATA_ROOT:/data soliareofastora/metagenomic-deepfri

**Comment by crusher083** [comment]
Yeap, we also build a lot of dockers on my dockerhub profile. There should be an institutional one.

**Comment by valentynbez** [comment]
Running with docker is deprecated.
