### ISSUE TITLE
Pyopal not found

### ISSUE THREAD

**Issue by lmszydlowski** [bioinf-mcb/Metagenomic-DeepFRI#73]
I receive an error 'pyopal not found' even though I have pyopal installed. I receive the same error regardless if I have pyopla 0.5.1 or 0.4.1 (as recommended)

**Comment by valentynbez** [comment]
In order to diagnose the problem, I require more information. 
Please, run the following commands and copy the output here: 
```
conda list 
echo $CONDA_PREFIX
which python
```

**Comment by lmszydlowski** [comment]
VM#1 
# packages in environment at /home/lszydlowski/miniconda3/envs/deepfri:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anyio                     4.3.0                    pypi_0    pypi
archspec                  0.2.2                    pypi_0    pypi
aria2                     1.37.0               h347180d_1    conda-forge
biopython                 1.83            py311h459d7ec_0    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.26.0               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2                 pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
click                     8.1.7           py311h06a4308_0
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
coloredlogs               15.0.1                   pypi_0    pypi
cython                    3.0.8                    pypi_0    pypi
exceptiongroup            1.2.0              pyhd8ed1ab_2    conda-forge
flatbuffers               23.5.26                  pypi_0    pypi
foldcomp                  0.0.7                    pypi_0    pypi
gawk                      5.3.0                ha916aea_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.3                    pypi_0    pypi
httpx                     0.26.0                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                      pypi_0    pypi
iniconfig                 2.0.0              pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libdeflate                1.2                  h516909a_1    bioconda
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.45.1               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.5               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
mmseqs2                   14.7e284        pl5321h6a68c12_2    bioconda
mpfr                      4.2.1                h9458935_0    conda-forge
mpmath                    1.3.0                    pypi_0    pypi
ncurses                   6.4                  h59595ed_2    conda-forge
numpy                     1.26.4          py311h64a7726_0    conda-forge
nvidia-cublas             11.5.1.101               pypi_0    pypi
nvidia-cublas-cu11        2022.4.8                 pypi_0    pypi
nvidia-cublas-cu117       11.10.1.25               pypi_0    pypi
nvidia-cuda-runtime-cu114 11.4.148                 pypi_0    pypi
nvidia-cudnn              8.2.0.51                 pypi_0    pypi
nvidia-cudnn-cu11         8.5.0.96                 pypi_0    pypi
nvidia-cufft              10.4.2.58                pypi_0    pypi
nvidia-curand             10.2.4.58                pypi_0    pypi
openssl                   3.2.1                hd590300_0    conda-forge
ort-nightly-gpu           1.18.0.dev20240219001          pypi_0    pypi
packaging                 23.2               pyhd8ed1ab_0    conda-forge
perl                      5.32.1          7_hd590300_perl5    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
pluggy                    1.4.0              pyhd8ed1ab_0    conda-forge
protobuf                  4.25.3                   pypi_0    pypi
pyopal                    0.5.1                    pypi_0    pypi
pysam                     0.22.0                   pypi_0    pypi
pytest                    8.0.1              pyhd8ed1ab_1    conda-forge
python                    3.11.0          he550d4f_1_cpython    conda-forge
python_abi                3.11                    4_cp311    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0                   pypi_0    pypi
scipy                     1.12.0          py311h64a7726_2    conda-forge
setuptools                69.1.0             pyhd8ed1ab_1    conda-forge
sniffio                   1.3.0                    pypi_0    pypi
sympy                     1.12                     pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
tzdata                    2024a                h0c530f3_0    conda-forge
urllib3                   2.2.1                    pypi_0    pypi
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge

echo $CONDA_PREFIX
/home/lszydlowski/miniconda3/envs/deepfri

which python
/home/lszydlowski/miniconda3/envs/deepfri/bin/python


VM#2
# packages in environment at /home/lukasz/miniconda3/envs/deepfri:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anyio                     4.3.0                    pypi_0    pypi
archspec                  0.2.3                    pypi_0    pypi
aria2                     1.37.0               h347180d_1    conda-forge
biotite                   0.39.0          py310hcc13569_0    conda-forge
brotli-python             1.1.0           py310hc6cd4ac_1    conda-forge
bzip2                     1.0.8                hd590300_5    conda-forge
c-ares                    1.27.0               hd590300_0    conda-forge
ca-certificates           2024.2.2             hbcca054_0    conda-forge
certifi                   2024.2.2           pyhd8ed1ab_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.7           unix_pyh707e725_0    conda-forge
coloredlogs               15.0.1                   pypi_0    pypi
cython                    3.0.9                    pypi_0    pypi
exceptiongroup            1.2.0                    pypi_0    pypi
flatbuffers               24.3.6                   pypi_0    pypi
foldcomp                  0.0.7                    pypi_0    pypi
gawk                      5.3.0                ha916aea_0    conda-forge
gettext                   0.21.1               h27087fc_0    conda-forge
gmp                       6.3.0                h59595ed_0    conda-forge
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.4                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
humanfriendly             10.0                     pypi_0    pypi
icu                       73.2                 h59595ed_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 h41732ed_0    conda-forge
libblas                   3.9.0           21_linux64_openblas    conda-forge
libcblas                  3.9.0           21_linux64_openblas    conda-forge
libdeflate                1.2                  h516909a_1    bioconda
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 13.2.0               h807b86a_5    conda-forge
libgfortran-ng            13.2.0               h69a702a_5    conda-forge
libgfortran5              13.2.0               ha4646dd_5    conda-forge
libgomp                   13.2.0               h807b86a_5    conda-forge
libiconv                  1.17                 hd590300_2    conda-forge
libidn2                   2.3.7                hd590300_0    conda-forge
liblapack                 3.9.0           21_linux64_openblas    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libopenblas               0.3.26          pthreads_h413a1c8_0    conda-forge
libsqlite                 3.45.1               h2797004_0    conda-forge
libssh2                   1.11.0               h0841786_0    conda-forge
libstdcxx-ng              13.2.0               h7e041cc_5    conda-forge
libunistring              0.9.10               h7f98852_0    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libxml2                   2.12.5               h232c23b_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
mdeepfri                  1.1.2                    pypi_0    pypi
mmseqs2                   14.7e284        pl5321h6a68c12_2    bioconda
mpfr                      4.2.1                h9458935_0    conda-forge
mpmath                    1.3.0                    pypi_0    pypi
msgpack-python            1.0.7           py310hd41b1e2_0    conda-forge
ncurses                   6.4                  h59595ed_2    conda-forge
networkx                  3.2.1              pyhd8ed1ab_0    conda-forge
numpy                     1.26.4          py310hb13e2d6_0    conda-forge
onnxruntime-gpu           1.17.1                   pypi_0    pypi
openssl                   3.2.1                hd590300_0    conda-forge
packaging                 23.2                     pypi_0    pypi
perl                      5.32.1          7_hd590300_perl5    conda-forge
pip                       24.0               pyhd8ed1ab_0    conda-forge
protobuf                  4.25.3                   pypi_0    pypi
pyopal                    0.4.1                    pypi_0    pypi
pysam                     0.21.0                   pypi_0    pypi
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.10.0          h543edf9_3_cpython    conda-forge
python_abi                3.10                    4_cp310    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
setuptools                69.1.1             pyhd8ed1ab_0    conda-forge
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.45.1               h2c6b66d_0    conda-forge
sympy                     1.12                     pypi_0    pypi
tk                        8.6.13          noxft_h4845f30_101    conda-forge
typing-extensions         4.10.0                   pypi_0    pypi
tzdata                    2024a                h0c530f3_0    conda-forge
urllib3                   2.2.1              pyhd8ed1ab_0    conda-forge
wget                      1.20.3               ha35d2d1_1    conda-forge
wheel                     0.42.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge

echo $CONDA_PREFIX
/home/lukasz/miniconda3/envs/deepfri

which python
/home/lukasz/miniconda3/envs/deepfri/bin/python

**Comment by valentynbez** [comment]
Hello! 
Unfortunately, I cannot reproduce the error. Could you run a clean install and copy paste log of the install and the error if appears again here? 
It is possible, that something wasn't properly compiled during installation, but I would need to see pip logs for it.

**Comment by lmszydlowski** [comment]
Hi, attached is the error log after installing mDF.
[deepFRI_error_log.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14571658/deepFRI_error_log.txt)

Btw, there is no "pip install ." in the installation step. Is it no longer necessary?

**Comment by valentynbez** [comment]
In this log there is only `deepfri` installation, it is successful. 
Please, install the whole environment again, because since `v1.1.2` `deepfri` is available from `PyPi` and is installed automatically with the environment. 
Please, do not use `sudo` as it might result in conflicting installation outside of the dedicated `conda` environment, which is the likely explanation of your error. 
To sum up: 
1. Reinstall the `deepfri` with environment installation step according to the manual.
2. Run commands without `sudo`.

**Comment by lmszydlowski** [comment]
Installed correctly this time and models were obtained, database built (afdb_swissprot_v4), but new error appeared (see log file)
[log.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14574035/log.txt)
