### ISSUE TITLE
Problem with running the pipeline

### ISSUE THREAD

**Issue by lmszydlowski** [bioinf-mcb/Metagenomic-DeepFRI#76]
[log2.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14590208/log2.txt)
[log3.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14590209/log3.txt)

After installing mDF on 2 different VMs with afdb_swissprot v4 and 2 different queries (bacterial proteomes, previously annotated) I encounter the following errors (see attached logs). In both cases it tries to align the sequences against python3.

**Comment by valentynbez** [comment]
This is weird, please attach commands you used. 
I used input you'd supplied in #73 and, contrary to your log, I do find hits against `afdb_swissprot_v4`. Looks like your database might be corrupt. It can happen if you interrupt `mDeepFRI` during database building with `mmseqs`. 
```
[2024-03-13 18:05:59] pipeline.predict_protein_function INFO: Aligning 2977 sequences against afdb_swissprot_v4
[2024-03-13 18:06:11] mmseqs.filter_mmseqs_results INFO: 3013 pairs after filtering with k=5 best hits.
[2024-03-13 18:06:12] pipeline.predict_protein_function INFO: Aligned 315 sequences.
```

**Comment by lmszydlowski** [comment]
mDeepFRI predict-function -i {FILE.faa} -d /foldcomp_database/afdb_swissprot_v4 -w weights -o /mDF_output

I downloaded afdb_swissprot_v4 from the foldcomp database

**Comment by lmszydlowski** [comment]
[log4.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14593290/log4.txt)

same problem

**Comment by valentynbez** [comment]
Could you please attach last input as well? 
I am struggling to replicate the error.

**Comment by lmszydlowski** [comment]
it is the same, but with --overwrite flag
