### ISSUE TITLE
Wrong headers in `MMseqs2` results

### ISSUE THREAD

**Issue by PawelSzczerbiak** [bioinf-mcb/Metagenomic-DeepFRI#8]
@lmszydlowski noticed that for some input `.faa` files the pipeline doesn't predict any GCNs. The problem arises when one uses the following headers:

`>gnl|extdb|pgaptmp_000002`

or more generally:

`>gnl|extdb|pgaptmp_000002 MFS transporter [Microbacterium]`

In such case the `alignments.json` file is always empty. It's not hard to check that it's because of inconsistent header naming in `mmseqs2_search_results.m8`, namely for the above cases we'are getting:

`pgaptmp_000002`

instead of: 

`gnl|extdb|pgaptmp_000002`

As a result, the `MMseqs2` search results are "not visible" and skipped. This can be a major issue because that kind of formatting is very frequently outputted by external bioinformatic tools.

**Comment by SoliareofAstora** [comment]
Problem occurs when we are creating mmseqs database. It's performed in 2 places

1) searching for similar sequences
2) creating new target database 

I couldn't find any createdb parameter inside mmseqs2 reference guide, so we will have to use a workaround. 
I propose hashing sequences IDs. It will work flawlessly for searching similar sequences before alignment. 

@tkosciol Is it OK  to hash target database sequence ids as well? It would solve the future issue of adding new protein structures with headers containing | to the target database

**Comment by SoliareofAstora** [comment]
Workaround https://github.com/bioinf-mcb/Metagenomic-DeepFRI/commit/38ad86d77ba62aae6ae40de4f96431730aee5d76
