### ISSUE TITLE
Unable to index afdb_uniprot database

### ISSUE THREAD

**Issue by lmszydlowski** [bioinf-mcb/Metagenomic-DeepFRI#82]
With mDF v1.1.5. I was unable to use Uniprot database, as it was indexed into 8 files: -rw-r--r-- 1 root root 1.1T Apr  3 18:17 afdb_uniprot_v4
-rw-r--r-- 1 root root    4 Apr  5 09:18 afdb_uniprot_v4.dbtype
-rw-r--r-- 1 root root  40G Apr  5 12:31 afdb_uniprot_v4.fasta.gz
-rw-r--r-- 1 root root 5.6G Apr  5 09:21 afdb_uniprot_v4.index
-rw-r--r-- 1 root root 8.5G Apr  5 09:24 afdb_uniprot_v4.lookup
-rw-r--r-- 1 root root  65G Apr  5 12:51 afdb_uniprot_v4.mmseqsDB
-rw-r--r-- 1 root root    4 Apr  5 12:51 afdb_uniprot_v4.mmseqsDB.dbtype
-rw-r--r-- 1 root root 6.8G Apr  5 12:48 afdb_uniprot_v4.mmseqsDB_h
-rw-r--r-- 1 root root    4 Apr  5 12:48 afdb_uniprot_v4.mmseqsDB_h.dbtype
-rw-r--r-- 1 root root 4.7G Apr  5 12:56 afdb_uniprot_v4.mmseqsDB_h.index
-rw-r--r-- 1 root root 371M Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.0
-rw-r--r-- 1 root root  83G Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.1
-rw-r--r-- 1 root root  82G Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.2
-rw-r--r-- 1 root root  82G Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.3
-rw-r--r-- 1 root root  82G Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.4
-rw-r--r-- 1 root root  82G Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.5
-rw-r--r-- 1 root root  82G Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.6
-rw-r--r-- 1 root root  82G Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.7
-rw-r--r-- 1 root root    4 Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.dbtype
-rw-r--r-- 1 root root 1.3K Apr  5 14:05 afdb_uniprot_v4.mmseqsDB.idx.index
-rw-r--r-- 1 root root 5.1G Apr  5 12:54 afdb_uniprot_v4.mmseqsDB.index
-rw-r--r-- 1 root root 8.8G Apr  5 12:58 afdb_uniprot_v4.mmseqsDB.lookup
-rw-r--r-- 1 root root   27 Apr  5 12:47 afdb_uniprot_v4.mmseqsDB.source
-rw-r--r-- 1 root root  39M Apr  5 09:24 afdb_uniprot_v4.source

Manual merging afdb_uniprot_v4.mmseqsDB.idx.0-7 files into afdb_uniprot_v4.mmseqsDB.idx did not solve the problem.

[log_v115_jc-1475_afdb_uniprot.txt](https://github.com/bioinf-mcb/Metagenomic-DeepFRI/files/14918991/log_v115_jc-1475_afdb_uniprot.txt)

**Comment by valentynbez** [comment]
Uniprot contains 214M sequnces, there will be a lot of technical challenges in making it work. 
There are no plans to include it.
